---
- name: "Copy artifact zip"
  ansible.builtin.copy:
    src: /root/project/artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: "extract zip file"
  shell: |
    cd ~/
    tar -xvzf artifact.tar.gz

# - name: "install and start node"
#   shell: |
#     cd .
#     npm install
#     pm2 stop default
#     pm2 start npm -- start
